### ISSUE TITLE
DLL links are missing "path"

### ISSUE THREAD

**Issue by staring-frog** [Cairath/Oxygen-Not-Included-Modding#4]
Thanks for a great project, really helps to start in a mod making!
I had an issue though: while following a guide I created a VS project from template and it had DLL links "path" fields empty, even though I copied DLLs to "lib" as it was suggested I had to re-create all of the links by hand anyway.

**Comment by staring-frog** [comment]
It turns out guide is misleading: it says to put lib next to .sln file, but actually "lib" needs to go next to a repo dir.

**Comment by Cairath** [comment]
Sorry for the super long delay -- we've double checked that the guide is correct. When selecting a project, the 'put project files in the solution directory' cannot be selected, that has been specified. Sometimes it helps to restart VS if it's not picking up on references.
