### ISSUE TITLE
Unclear wiki referencing

### ISSUE THREAD

**Issue by staring-frog** [Cairath/Oxygen-Not-Included-Modding#5]
The reference in https://github.com/Cairath/Oxygen-Not-Included-Modding/wiki/Publishing#local-install is not clear, it says:
"If you want your mod to behave different upon a crash, see the development section for more info on the mods\Dev folder."
But there's no development section anymore, it's Introduction:testing https://github.com/Cairath/Oxygen-Not-Included-Modding/wiki/Introduction#testing-the-mod.

**Comment by Cairath** [comment]
This section has been rephrased
